website/srcs/game/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
from .views import GameSessionViewSet, GameMoveViewSet

app_name = 'game'

router = routers.DefaultRouter()
router.register(r'sessions', GameSessionViewSet)
router.register(r'moves', GameMoveViewSet)


urlpatterns = [
    path('', views.index, name='index'),
    path('', include(router.urls)),
]

website/srcs/leaderboards/urls.py
from django.urls import path
from . import views

app_name = 'leaderboards'

urlpatterns = [
    path('', views.index, name='index'),
]

website/srcs/transendence/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
# from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', views.index, name='home'),
    path('api/users/', include('users.urls')),
    path('api/game/', include('game.urls')),
    path('api/leaderboards/', include('leaderboards.urls')),
    path('api/blockchain/', include('blockchain.urls')),
	path('api/messaging/', include('messaging.urls')),
	path('api/tournaments/', include('tournaments.urls')),

    # path('api/tournaments/', include('tournaments.urls')),
    # path('users/', include('users.urls')),
    # path('game/', include('game.urls')),
    # path('leaderboards/', include('leaderboards.urls')),
    # path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/srcs/users/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
from .views import UserProfileViewSet
from django.contrib.auth.views import LogoutView

app_name = 'users'
# Définir le routeur pour les routes API
router = routers.DefaultRouter()
router.register(r'profiles', UserProfileViewSet)

urlpatterns = [
    # path('', views.index, name='index'),
    # Routes API pour les profiles d'utilisateurs
    path('', include(router.urls)),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
]

website/srcs/transendence/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

website/srcs/transendence/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Mon site{% endblock %}</title>
    {% load static %}

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <!-- Favicon -->
    <link
      rel="icon"
      href="{% static 'favicon/favicon.ico' %}"
      type="image/x-icon"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />

    <!-- CSS  -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'users/css/profile.css' %}" />
    <link rel="stylesheet" href="{% static 'game/css/game.css' %}" />
    <link rel="stylesheet" href="{% static 'messaging/css/chat.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'tournaments/css/tournaments.css' %}"
    />

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Climate+Crisis&family=Handjet:wght,ELGR,ELSH@100..900,1..2,0..16&display=swap"
      rel="stylesheet"
    />
  </head>

  <body class="main-body">
    <div
      id="landing-page"
      class="d-flex justify-content-center align-items-center vh-100 flex-column"
    >
      <h1 id="animated-title"></h1>
      <div id="button-container" class="hidden"></div>
      <footer class="text-center fixed-bottom">
        <p>By Kazuma, Neah & Martzoni</p>
      </footer>
    </div>

    <!-- Navbar -->
    <div id="main-page" class="d-none">
      <nav
        class="navbar navbar-light w-100 border-bottom border-white p-2"
      >
        <a class="navbar-brand title" href="#">Transcendence</a>

        <div
          class="d-flex column-gap-3 justify-content-center align-items-center"
        >
          <a id="nav-bar-username"> </a>
          <a
            id="nav-bar-login-btn"
            class="custom-btn btn btn-outline-light btn-lg"
            href="#login"
          >
            Log In
          </a>
          <button
            class="btn btn-sm"
            type="button"
            data-bs-toggle="offcanvas"
            data-bs-target="#offcanvasRight"
            aria-controls="offcanvasRight"
            id="menu-btn"
          >
            <i class="fa-solid fa-ellipsis-vertical"></i>
          </button>
        </div>
      </nav>

      <!-- Toggleable SideBar -->

      <div
        class="offcanvas offcanva-custom glassmorphism-block offcanvas-end"
        data-bs-backdrop="true"
        tabindex="-1"
        id="offcanvasRight"
        aria-labelledby="offcanvasRightLabel"
      >
        <div class="offcanvas-body">
          <ul
            class="nav d-flex flex-column justify-content-evenly align-items-center h-100"
          >
            <li class="nav-item">
              <a class="btn btn-lg position-relative" href="#profile">
                <i class="fa-solid fa-user"> </i
                ><span
                  id="friend-request-badge"
                  class="badge rounded-pill d-none notification-badge position-absolute"
                >
                  0
                </span>
              </a>
            </li>
            <li class="nav-item">
              <a class="btn btn-lg" href="#chat">
                <i class="fas fa-comments"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="btn btn-lg" href="#game">
                <i class="fa-solid fa-table-tennis-paddle-ball"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="btn btn-lg" href="#tournaments">
                <i class="fa-solid fa-trophy"></i>
              </a>
            </li>
            <li class="nav-item">
              <a class="btn btn-lg">
                <i
                  id="logout-button"
                  class="fa-solid fa-right-from-bracket"
                >
                </i>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <main
        id="app"
        class="d-flex justify-content-center align-items-center v-100"
      ></main>
    </div>

    <script>
      let currentUser = "{{ request.user.username }}"; // Injecter le nom d'utilisateur dans une variable JS
    </script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>

    <!-- JavaScripts -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/router.js' %}"></script>
    <script src="{% static 'users/js/signup.js' %}"></script>
    <script src="{% static 'users/js/login.js' %}"></script>
    <script src="{% static 'users/js/profil.js' %}"></script>
    <script src="{% static 'game/js/game.js' %}"></script>
    <script src="{% static 'messaging/js/messaging.js' %}"></script>
    <script src="{% static 'tournaments/js/tournaments.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </body>
</html>

website/srcs/transendence/templates/index.html
{% extends "base.html" %}

{% block title %}Accueil{% endblock %}

{% block extra_head %}
{% endblock %}

{% block content %}
<div class="centered-container">
	<h1 class="bungee-shade-regular">Bienvenue sur Transcendence</h1>
	<ul>
		<li><a href="{% url 'game:index' %}">Jouer à Pong</a></li>
		{% comment %} <li><a href="{% url 'users:index' %}">Gestion des Utilisateurs</a></li> {% endcomment %}
		<li><a href="{% url 'leaderboards:index' %}">Classements</a></li>
	</ul>
</div>
{% endblock %}